# This is only an example. Most values are dummy placeholders just to match the
# types; they are often not optimal and must be tuned.

[control]
version = 3
online = false

state_file = '/data/train/Mortal/to/mortal.pth'
best_state_file = '/data/train/Mortal/to/best.pth'
tensorboard_dir = '/data/train/Mortal/to/dir'

device = 'cuda:0'
enable_cudnn_benchmark = false
enable_amp = false

batch_size = 512
opt_step_every = 1

save_every = 400
test_every = 20000
#submit_every = 400
submit_every = 10000

# using env `TRAIN_PLAY_PROFILE`
[train_play.default]
games = 800
log_dir = '/data/train/Mortal/to/train_play'
boltzmann_epsilon = 0.005
boltzmann_temp = 0.05
repeats = 2

[test_play]
games = 3000
log_dir = '/data/train/Mortal/to/test_play'

[dataset]
globs = ['/data/train/Mortal/to/dataset/mjai/*/*']
file_index = '/data/train/Mortal/to/file_index.pth'
file_batch_size = 15
num_workers = 1
player_names_files = ['/data/train/Mortal/to/dataset/playname']
num_epochs = 1
enable_augmentation = false
augmented_first = false

[env]
gamma = 1
pts = [3.0, 1.5, 0.0, -4.5]
#pts = [3.0, 1.7, -0.2, -4.5]

[resnet]
conv_channels = 192
num_blocks = 40

[cql]
min_q_weight = 5

[aux]
next_rank_weight = 0.2

[freeze_bn]
# `true` in online training
mortal = false

[bn_attrs]
momentum = 0.01
eps = 1e-3

[optim]
eps = 1e-8
betas = [0.9, 0.999]
weight_decay = 0.1
max_grad_norm = 0

[optim.scheduler]
peak = 1e-5
final = 1e-5
warm_up_steps = 0
max_steps = 0

[baseline.train]
device = 'cuda:0'
state_file = '/data/train/Mortal/to/baseline.pth'

[baseline.test]
device = 'cuda:0'
state_file = '/data/train/Mortal/to/baseline.pth'

[online]
history_window = 50

[online.remote]
host = '127.0.0.1'
port = 5000

[online.server]
buffer_dir = '/data/train/Mortal/to/buffer'
drain_dir = '/data/train/Mortal/to/drain'
sample_reuse_rate = 0
sample_reuse_threshold = 0
capacity = 3600
force_sequential = false

[test]
stochastic_latent = false

[1v3]
games_per_iter = 2000
iters = 500
log_dir = '/data/train/Mortal/to/1v3'

[1v3.challenger]
device = 'cuda:0'
name = 'mortal'
state_file = '/data/train/Mortal/to/mortal.pth'
stochastic_latent = false
enable_amp = true
enable_rule_based_agari_guard = true

[1v3.champion]
device = 'cuda:0'
name = 'baseline'
state_file = '/data/train/Mortal/to/baseline.pth'
stochastic_latent = false
enable_amp = true
enable_rule_based_agari_guard = true

[1v3.akochan]
enabled = false
dir = '/data/train/Mortal/to/akochan'
tactics = '/data/train/Mortal/to/tactics.json'

[grp]
state_file = '/data/train/Mortal/to/grp.pth'

[grp.network]
hidden_size = 64
num_layers = 2

[grp.control]
device = 'cuda:0'
enable_cudnn_benchmark = false
tensorboard_dir = 'grp_v2.1/log'

batch_size = 512
save_every = 2000
val_steps = 400

[grp.dataset]
train_globs = [
    '/data/train/Mortal/to/dataset/mjai/*/*',
    # ...
]
val_globs = [
    '/data/train/Mortal/to/dataset/mjai/0/*',
    # ...
]
file_index = '/data/train/Mortal/to/grp_file_index.pth'
file_batch_size = 50

[grp.optim]
lr = 1e-5
